### ISSUE TITLE
Use v2 of keepalive-workflow

### ISSUE THREAD

**Issue by rfay** [ddev/github-action-add-on-test#27]
keepalive-workflow@v2 is now available, which does not require the dummy commits every 2 months. Consider using it.

https://github.com/gautamkrishnar/keepalive-workflow/releases/tag/2.0.0

**Comment by rfay** [comment]
I guess this also requires a change to the `permission` statement, so perhaps we need a new major version of this action to support it?

**Comment by julienloizelet** [comment]
> I guess this also requires a change to the `permission` statement, so perhaps we need a new major version of this action to support it?


Yes, from what I understand in the "[migrating from v1 to v2](https://github.com/gautamkrishnar/keepalive-workflow/releases/tag/2.0.0)" section, the user of our github action will have to modify the permission part accordingly in order to have a functional keepalive step.

I consider this is a breaking change and will create a "v2" major tag for the release.

**Comment by rfay** [comment]
I guess since users will have to change to @v2 and such, we'll gradually switch over and we'll have experience with it in case it doesn't work as advertised.
